# Generated by Django 4.1 on 2023-04-24 16:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BreakFast',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('mealname', models.CharField(max_length=30)),
                ('voteCount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Voted',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=30)),
                ('timeVoted', models.DateTimeField(default=datetime.datetime(2023, 4, 24, 16, 20, 41, 371336))),
            ],
        ),
    ]
