# Generated by Django 4.1 on 2023-04-24 16:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breakfast',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='voted',
            name='timeVoted',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 24, 16, 35, 10, 642032)),
        ),
    ]
