# Generated by Django 4.1 on 2023-04-24 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_breakfast_id_alter_voted_timevoted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voted',
            name='timeVoted',
            field=models.DateTimeField(),
        ),
    ]
