# Generated by Django 4.1 on 2023-04-23 18:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_breakfast_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voted',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user', models.CharField(max_length=30)),
                ('timeVoted', models.DateTimeField(default=datetime.datetime(2023, 4, 23, 18, 1, 28, 648077))),
            ],
        ),
    ]
